version: '3.6'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=tracker_db
      - POSTGRES_USER=tracker_user
      - POSTGRES_PASSWORD=tracker_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=tracker.settings
    entrypoint:
      - ./docker/scripts/wait-for-it.sh
      - --timeout=10
      - db:5432
      - --
    command: ["django-admin", "runserver", "0:5000"]
    volumes:
      - .:/tracker
    ports:
      - "5000:5000"
    depends_on:
      - db